name: Publish on GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      #- name: Add CNAME file
      # run: echo "toscalabs.org" > themes/tosca-theme/static/CNAME

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
